### PR TITLE
Removed addressable gem

### LINKED ISSUE #18: Adressable 2.2.9 breaks
see https://github.com/sporkmonger/addressable/issues/77. Support for nested query parameters has been removed in 2.2.9, 2.2.8 is working just fine.

### PR DESCRIPTION
**Pull request by gregory-m**
As you know addressable gem author drop support for nested params. So I use Rack::Utils.parse_nested_query instead.

This also fix #18

### CODE REVIEW

**Comment by gregory-m** [comment]
Hmm, The Travis build failed in weird place. Only for 1.9.3 and I can't reproduce this locally. I think this TimeCop related issue.

**Comment by Xylakant** [comment]
looks fine to me, I'll have a look at the build-issues before merging. Thanks for the patch.

**Comment by Xylakant** [comment]
After merging this pull request I get local build failures, but travis seems to indicate everything is fine. So use with caution.

**Comment by gregory-m** [comment]
Hmm, tested locally on 1.9.3 and jruby without any issues.

Where exactly tests fails?

**Comment by Xylakant** [comment]
fails in the faraday integration test that you added. However, as I said it passes on travis just fine. The trace I get is 

```
/Users/fgilcher/Projects/warden-hmac-authentication/test/faraday/request/hmac_test.rb:76:in `block (4 levels) in <top (required)>': undefined method `headers' for #<Faraday::Builder:0x00000100f172e0 @handlers=[]> (NoMethodError)
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/faraday-0.7.5/lib/faraday/connection.rb:42:in `block in initialize'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/faraday-0.7.5/lib/faraday/builder.rb:12:in `block in create'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/faraday-0.7.5/lib/faraday/builder.rb:65:in `build'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/faraday-0.7.5/lib/faraday/builder.rb:54:in `initialize'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/faraday-0.7.5/lib/faraday/builder.rb:12:in `new'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/faraday-0.7.5/lib/faraday/builder.rb:12:in `create'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/faraday-0.7.5/lib/faraday/connection.rb:42:in `initialize'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/faraday-0.7.5/lib/faraday.rb:10:in `new'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/faraday-0.7.5/lib/faraday.rb:10:in `new'
    from /Users/fgilcher/Projects/warden-hmac-authentication/test/faraday/request/hmac_test.rb:75:in `block (3 levels) in <top (required)>'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/situation.rb:42:in `instance_eval'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/situation.rb:42:in `setup'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/runnable.rb:49:in `run'
  5 Changelog
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/context.rb:101:in `block in local_run'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/context.rb:101:in `each'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/context.rb:101:in `local_run'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/context.rb:91:in `run'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/context.rb:135:in `block in run_sub_contexts'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/context.rb:135:in `each'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/context.rb:135:in `run_sub_contexts'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/context.rb:92:in `run'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot.rb:39:in `block (2 levels) in run'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot.rb:39:in `each'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot.rb:39:in `block in run'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot/reporter.rb:45:in `summarize'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot.rb:38:in `run'
    from /Users/fgilcher/.rvm/gems/ruby-1.9.3-p125/gems/riot-0.12.3/lib/riot.rb:109:in `block in <module:Riot>'
rake aborted!
```

It's probably something with my local setup, but I thought it's good to advise caution. I'll roll this into a release once I figured out why it fails for me.

**Comment by Xylakant** [comment]
Ok, it fails with an old version of faraday. I had 0.7.5 installed, an update to 0.8.4 fixes it. I assume that you're using a method that was only added later.

**Comment by Xylakant** [comment]
pushed as 0.6.3
